### ISSUE TITLE
Unable to access Factory Mode

### ISSUE THREAD

**Issue by kai-h** [cybercase/webminidisc#103]
I'm using Web MiniDisc that's hosted at https://web.minidisc.wiki/ as I believe that's the most up-to-date version.
I have tried with one Sony deck (MDS-S500) and two Sony portables (MZ-NH600 and MZ-RH1) and none of these devices have a Factory Mode in the ... menu.
Are there only particular devices that support Factory Mode?

**Comment by asivery** [comment]
Hello @kai-h ,
The factory mode is only accessible on Sony NetMD portables. The MDS-S500 is a deck and both the portables you listed are HiMD devices - unfortunately none of them support the factory mode.

**Comment by kai-h** [comment]
Thank you, that all makes sense. I'll have to add another recorder to my collection!
