### ISSUE TITLE
Feature request: Tell me if all the tracks I want to copy will fit before recording

### ISSUE THREAD

**Issue by foxmajik** [cybercase/webminidisc#104]
The app obviously knows how long each track is, so it should be able to tell me if the tracks I'm dropping on will fit onto the disc before it starts recording. If they won't it should present a modal informing me the tracks might not fit. It should also select the correct LP mode to fit all of the tracks, but in doing so it should notify me that it is switching the mode, perhaps by putting a red frame around the LP mode selected or somesuch.

**Comment by asivery** [comment]
Hello @foxmajik ,
The feature you're proposing already exists in my fork of the app ([Web Minidisc Pro](https://web.minidisc.wiki)).
The tracks which wouldn't fit get marked in red, and changing the recording mode refreshes the list of what will fit and what won't.
Please let me know if that's what you had in mind.

**Comment by kai-h** [comment]
What would also be nice is a display of the total length of the selected tracks, and how much free space will be left on the disc after the selected tracks are recorded.
This would really help when making compilations when you want to fill every last minute of the disc!

**Comment by asivery** [comment]
Ooh, good idea @kai-h - I agree, it would help massively. I'll add it in the next update.

**Comment by asivery** [comment]
@kai-h Added in https://github.com/asivery/webminidisc/commit/6e76f88da8636dbac63c8086e0745a443ed8d79b

**Comment by asivery** [comment]
It should be a part of web.minidisc.wiki in a few days.
