### ISSUE TITLE
Accidentally including a .m3u file when dropping a selection of files causes a crash

### ISSUE THREAD

**Issue by foxmajik** [cybercase/webminidisc#105]
If I accidentally include a .m3u file in the files I have selected to record, the app will crash when it gets to that file in the recording queue.

**Comment by asivery** [comment]
Hi @foxmajik ,
Thanks for letting me know. I'll investigate the issue.

**Comment by asivery** [comment]
Fixed in https://github.com/asivery/webminidisc/commit/3115e76cf1efa59030911c0587c9da2f1c916e70
