### ISSUE TITLE
Feature Request - Batch Edits

### ISSUE THREAD

**Issue by kai-h** [cybercase/webminidisc#108]
As it takes 5 – 15 seconds each time an item is changed in the TOC, it can take a very long time to do wholesale edits of a disc - e.g. title a whole album worth of tracks or move tracks around into folders/groups.

Would it be possible to have a mode where the changes are made in RAM on the computer, and then there's an **Apply** button to apply all of the edits in one go?

**Comment by asivery** [comment]
@kai-h Fixed in upcoming Web Minidisc Pro v1.3.0
