### ISSUE TITLE
Cannot create folders

### ISSUE THREAD

**Issue by psykad** [cybercase/webminidisc#11]
The SonicStage software allows the creation of folders/groups. It'd be nice to have this as a feature.

**Comment by asivery** [comment]
I implemented group support in my fork. It's currently hosted at https://resources.minidisc.wiki/webminidisc
Please let me know what you think

**Comment by psykad** [comment]
@asivery this looks fantastic! I see you also posted in the platinum-md issue regarding this same request. Can't wait to see it implemented there, too.

**Comment by asivery** [comment]
Thanks so much for the feedback!

**Comment by cybercase** [comment]
Thanks for you impressive work @asivery .
I'm working to merge all of this into master soon

**Comment by cybercase** [comment]
#49 brings asivery's work on groups into master. Thanks.
