### ISSUE TITLE
Japanese Full-Width Input Broken (macOS)

### ISSUE THREAD

**Issue by depevauge** [cybercase/webminidisc#111]
It appears as if the full-width Hiragana and Katakana input methods are suddenly broken in v1.3.2.
For example, when I type in `w a t a shi`, I get `ｗあｔあｓｈい`, I should get `わたし` though. Only vowels, numbers, and other one-key inputs are handled correctly. 

Another issue I noticed is that some characters are not copied correctly when dragging/dropping files with Japanese characters into Web MiniDisc. Any Kana containing a _dakuten_ `゛` or _handakuten_ `゜` will be copied/transliterated incorrectly, for instance, `べ` becomes `へ・`.

None of these issues appear in normal-width editing mode. Also, copying/pasting Japanese text in full-width mode works just fine.

**Comment by asivery** [comment]
@depevauge, I was not able to reproduce the issue. Could you send me a screen capture showing this issue?

**Comment by GrayzerGray** [comment]
Hi. Not sure if this one was meant for me, you answered my Hi-MD support questions :-)Merry Christmas/Happy HolidaysSent from my iPhoneOn 25 Dec 2022, at 14:58, asivery ***@***.***> wrote:﻿
@depevauge, I was not able to reproduce the issue. Could you send me a screen capture showing this issue?

**Comment by depevauge** [comment]
> @depevauge, I was not able to reproduce the issue. Could you send me a screen capture showing this issue?

Ironically, the issue seems to have resolves itself, I couldn't reproduce it on any of my Macs, sorry. 😅
