### ISSUE TITLE
Homebrew mode not available on MDS-JE780

### ISSUE THREAD

**Issue by Micmac9** [cybercase/webminidisc#113]
Homebrew mode is not available on Sony MDS-JE780 Type-S recorder.
I tried different drivers, browsers and operating systems.
Any solution? I want to copy my old records back to my pc.

Thanks!

**Comment by Shadester** [comment]
Decks doesn't support homebrew mode. Only portables do.

**Comment by Micmac9** [comment]
Thanks!
Hopefully the Decks also will be supported for the homebrew  some day.
