### ISSUE TITLE
Support for a shuffled selection of audio files?

### ISSUE THREAD

**Issue by Flamekebab** [cybercase/webminidisc#115]
Bit of an odd one - would it be possible to have .m3u support or something similar?
Essentially I have a big mix of songs and would love to be able to drop them into webminidisc and have it fit a random selection on a disc. I'm not sure of the best way to accomplish this but I could see M3U working as a way to provide the relevant data (I could shuffle the list, save the file, and have webminidisc fill a disc with as many as will fit).

**Comment by asivery** [comment]
I think it should be possible to accomplish this with external software.
You can instead copy a random selection of files to a separate directory with some script, then upload all of these files with Web Minidisc.

**Comment by Flamekebab** [comment]
The issue is more related to running time. Getting a random selection of files is relatively easy but continuing to select until SP/LP2/LP4 is filled for a given disc size is the tricky part.

**Comment by Flamekebab** [comment]
Took me a while to get around to it but if anyone else wants this functionality I've written a script that does the heavy lifting: https://github.com/Flamekebab/md_disc_filler
