### ISSUE TITLE
"Error uploading to device" on Sharp IM-DR420

### ISSUE THREAD

**Issue by andyboeh** [cybercase/webminidisc#12]
I recently acquired a Sharp IM-DR420 NetMD recorder. When uploading a track, it always reports "Error uploading to device" no matter if it's SP, LP2 or LP4. 

I have similar problem with netmdcli, so I suppose there is a protocol problem. The device works fine using Sonic Stage and I have USB traces at hand. It would be nice if somebody could point me in the right direction.

A similar issue was created at https://github.com/linux-minidisc/linux-minidisc/issues/65, I don't know where this is best kept.

**Comment by cybercase** [comment]
Hello @andyboeh 

WebMiniDisc is just a web UI built upon the amazing work done by the linux-minidisc project. I think the best place to report and discuss this issue is in the linux-minidisc project itself.

When a solution is found, I'll gladly take care of porting the fix to WebMiniDisc.

**Comment by andyboeh** [comment]
As mentioned in the referenced issue, the Sharp device requires exclusive access. I just checked netmd-js, the functions `acquire()` and `release()` are already present, so it might just be a matter of calling them - `acquire()` needs to be called before the secure session is started.

**Comment by cybercase** [comment]
@andyboeh I've merged your PRs. Thanks for the work you've done.

I'm currently publishing an updated version of the app.

Keep in mind that you'll get the update only after the Service Worker finished downloading the new bundle and the app has been reloaded (refreshing the page is not enough... you actually need to close the tab).

If anything's wrong, let me know.

**Comment by andyboeh** [comment]
Thanks for your hard work! I just tested the updated version on your server and I could successfully transfer tracks to my Sharp device and renaming tracks works as well.
