### ISSUE TITLE
Feature request: export TOC data to flat file

### ISSUE THREAD

**Issue by woookash** [cybercase/webminidisc#123]
I'm currently archiving my collection of MD - and it works mostly great - thanks a lot for the work that has been done and allows for that - it's a lot of memories back from late 90ies early 2000 for me :)
One feature I'm missing a bit would be an export of the TOC - including the datetime stamps.
Could be a simple .csv file, but with all the useful information:
Title of the disc, if any
1 line per track, including all available infos: track title, if any, datetime, length

Really doesn't have to be "nice" as it's purely for archiving purposes - maybe this file could be created as part of the "archive disc" existing flow.

**Comment by asivery** [comment]
@woookash Have you tried "Export titles to CSV" in the standard (non-homebrew) mode? I think that should export a file with a similar format to the one you're talking about.
