### ISSUE TITLE
Dropouts in playback only with 80 minute disk

### ISSUE THREAD

**Issue by mlutker** [cybercase/webminidisc#124]
Sony MZ-S1
I'm getting pauses in playback on my Kenwood deck and players (both sony and kenwood) at random points. I thought it was just 80 minute disc.. was wrong. It is stopping at just random points then starting where it left off. As if there is more data than it can take. SP mode.. 74 minutes. It is all over in playback. Sometimes it just ends and goes to the next song.

Not getting on mdlp mode

**Comment by asivery** [comment]
Most likely just the hardware failing. Try lubricating the rails / cleaning the laser @mlutker
