### ISSUE TITLE
MZ-NH600D Not compatible

### ISSUE THREAD

**Issue by y84media** [cybercase/webminidisc#129]
Hello,

I have a Sony MZ-NH600D on a 2018 Intel Mac Mini running Ventura (13.3.1) using a USB-C to USB-A adapter.
I know that the computer can see the MD Player because when I insert a disc with music on it, the "NO NAME" icon pops up on the desktop, and I can open it and see the "HMDHIFI" folder & the .HMA files inside.

I've also tried ejecting the "NO NAME" icon and clicked on the "CONNECT" button in Web MiniDisc Pro, still says "Connection Failed" in red.

**Comment by asivery** [comment]
@y84media You're in HiMD mode, the current version of Web Minidisc only works with NetMD mode. HiMD mode is being worked on, but it's not ready yet.

EDIT: On the player, select "Options" > "Disc Mode" > "MD" - the device should switch to NetMD mode.

**Comment by cbmtrx** [comment]
@y84media I've used the NH600D model successfully. Follow asivery's instructions.
