### ISSUE TITLE
No Recording in Web Minidisc Pro

### ISSUE THREAD

**Issue by MarcioAyran** [cybercase/webminidisc#134]
Hello
I'm using the Web Minidisc and I tried to use the Web Minidisc Pro with my Sony MZ-N920 MD for recording, but when I drag-and-drop the songs to record a disc, the recording is converted, but the device doesn't record, unlike from the previous version (non-pro Web Minidisc). What can I do to use the Web Minidisc Pro version and avoid this problem?

**Comment by asivery** [comment]
Closing this since it's been moved to Web Minidisc Pro's repo.
