### ISSUE TITLE
NW-HD5 support

### ISSUE THREAD

**Issue by Invictaz** [cybercase/webminidisc#135]
The Sony NW-HD5 uses SonicStage or Sony MP3filemanager and does ATRAC3 and Mp3 playback.
Encryption key here:

http://www.waider.ie/hacks/workshop/c/mple/FILE_FORMAT_v2.txt

Only difference is HDD based player instead of minidisc.

@asivery 

Hopefully doable without a lot of hacks. It uses the same mini USB.
It would be nice to take out the harddrive and examine it, however since these units are rare (tried purchasing one for 4+ years) I do not dare to open it.

**Comment by asivery** [comment]
Responded in the WebMinidisc Pro issue.
