### ISSUE TITLE
[Feature Request] Confirmation on Wipe Disc

### ISSUE THREAD

**Issue by GaProgMan** [cybercase/webminidisc#14]
### Overview

I think it would be useful to have a confirmation on the Wipe Disc menu item. This would have the double purpose of:

1. Ensuring that the user is sure that they want to wipe the disc
1. Stopping people from "mis-clicking"

I'm not sure how often the second point happens, but I know from personal experience that I've clicked "Wipe Disc" a few times when I've been wanting to click "Rename". That's likely down to my pour mouse control or clicking too soon.

### Operation

1. User clicks on the "Wipe Disc" menu item
1. Modal is displayed asking for confirmation (i.e. "Are you sure?" "Yes" "No")
    1. If the user clicks "Yes" the disc is wiped
    1. Is the user clicks "No" the modal is dismissed

### Potential Impact

I believe that the impact would be relatively small and would only require changing one piece of code. Perhaps simply adding a method in the [handleWipeDisc](https://github.com/cybercase/webminidisc/blob/148b62265acd7082383ffee489770b0e03260c7a/src/components/topmenu.tsx#L32) method to prompt for confirmation would be all that is required.

**Comment by cybercase** [comment]
Hi @GaProgMan .
This makes total sense to me. Since the _Wipe Disc_ cannot be undoed, let's add a confirmation dialog.

I'll try to implement this as soon as I find some time (hopefully soon) :)

Thanks

**Comment by GaProgMan** [comment]
@cybercase would it be too far out of scope to add a "destructive action" modal? That way it could be reused for deleting tracks, too.

I can take a look at putting one together if you'd prefer. I have a little spare time at the moment and could try and throw something together.

**Comment by cybercase** [comment]
I think it's fine.
Both "Wipe Disc" and "Delete Track" are not undoable, so it make sense to ask for some confirmation.

If you want, I'll gladly let you have fun with the code :)

Currently all the dialogs are instantiated at the bottom of `src/components/main.tsx` and controlled via redux.
However, if you want to experiment with react context or any other pattern I'm totally fine with that.

Let me know if you need help.
