### ISSUE TITLE
Offline apk

### ISSUE THREAD

**Issue by jamilroach** [cybercase/webminidisc#2]
Thanks for the great code! Magic! Is there any method of using this offline on an android phone?

**Comment by cybercase** [comment]
Hello @jamilroach . The app should work offline either on android or any other os.
You can use the _Add to Home screen_ menu item in chrome to install the app on your android phone.


![Screenshot_20200413-233315](https://user-images.githubusercontent.com/1076854/79163589-ab19df80-7ddf-11ea-83f0-5c42665dc22c.png)

**Comment by jamilroach** [comment]
Very cool! There is also a nice minidisc icon on the home-screen.
