### ISSUE TITLE
Media tags not working for FLAC files

### ISSUE THREAD

**Issue by basscheffers** [cybercase/webminidisc#20]
Thanks for adding media tags support! 👍 

But unfortunately, they do not seem to work for FLAC files, even though jsmediatags says it supports it.

**Comment by cybercase** [comment]
@basscheffers can't reproduce. Could you link the flac file you've tested?

**Comment by basscheffers** [comment]
Mystery solved! It turns out the ripper I used (dbPowerAmp) creates tags with keys like "Title". If I open the same file in a tag editor, or a player like Audirvana, it works just fine. But (presumably) jsmediatags is case sensitive to keys and doesn't read it.

In the screenshot, the bottom file was re-saved by a tag editor, and it works. In the top file I manually changed the "Title" key to "TITLE" in the hex editor and guess what? That was enough to make it work in Web Minidisc when I chose "Title" for track name.

So yeah, sounds like jsmediatags is the most likely culprit here? If they just make theirs case insensitive, it would fix it in Web Minidisc too.

Also attached is a small FLAC with the same issue.

Thanks!
Bas.

<img width="920" alt="Screen Shot 2020-09-17 at 9 10 33 pm" src="https://user-images.githubusercontent.com/1966616/93465678-4b91a400-f92a-11ea-9c8e-8a7fd5fe03ad.png">

[11 Will Smith - Keith B-Real II (Interlude).flac.zip](https://github.com/cybercase/webminidisc/files/5238852/11.Will.Smith.-.Keith.B-Real.II.Interlude.flac.zip)

**Comment by cybercase** [comment]
@basscheffers  Thanks for taking the time to look into this.
We could reach out to the jsmediatags maintainers by opening an issue and providing the steps to reproduce.
The fix is potentially easy, so we could also offer some help in crafting a PR.
Is this something you've time to do? Or should I take care when I'll have some free time?

**Comment by jjwbruijn** [comment]
Ref: https://github.com/aadsm/jsmediatags/issues/90
Seems folks already encountered the issue. Suggested fix was to use https://github.com/Borewit/music-metadata instead of jsmediatags, not sure how much effort that would entail...

**Comment by Shadester** [comment]
I will try to take a stab at it this weekend. The current lib uses `onSuccess:` handlers and music-metadata uses `async` call in the example, so some tweaking needs to be done. Also, I have no prior knowledge of node/typescript.
