### ISSUE TITLE
Connecting to MZ-RH1

### ISSUE THREAD

**Issue by fernando236** [cybercase/webminidisc#23]
Hola,
Trying to connect to my MZ-RH1 but I have the following alert > "The requested interface implements a protected class."

![Screenshot 2020-11-01 at 16 01 35](https://user-images.githubusercontent.com/73788549/97807478-619cbf00-1c61-11eb-9a02-57387f66d601.png)

Has anyone had the same issue? Any idea how to fix this? Thanks in advance

**Comment by Invictaz** [comment]
@deenine worked with the RH1 on linux

**Comment by cybercase** [comment]
Hello @fernando236 .
I don't own a MZ-RH1 so I'm not 100% sure of why you're getting this error. However, a few people told me that your RH1 should have a menu setting for Hi-MD or Standard mode. If that's the case, you'll need to set standard mode as the Hi-MD mode is not supported by Web MiniDisc.
Hope it helps.

**Comment by Invictaz** [comment]
@cybercase AFAIK that setting only affects recording not playback or USB. Dont pin me on that. Check the RH1 manual.

**Comment by fernando236** [comment]
> Hello @fernando236 .
> I don't own a MZ-RH1 so I'm not 100% sure of why you're getting this error. However, a few people told me that your RH1 should have a menu setting for Hi-MD or Standard mode. If that's the case, you'll need to set standard mode as the Hi-MD mode is not supported by Web MiniDisc.
> Hope it helps.

It works! Gracias @cybercase 

![Screenshot 2020-11-02 at 19 30 37](https://user-images.githubusercontent.com/73788549/97905418-3938c180-1d42-11eb-9651-3eccd4053836.png)
