### ISSUE TITLE
No handling for encoding errors

### ISSUE THREAD

**Issue by WaferMouse** [cybercase/webminidisc#24]
Sometimes the encoder will just hang on a file - this is unavoidable AFAIK, as the encoder still isn't perfect for eg. LP4. When this happens the only way forward is to back out of the app and go back into it. It would be nice if the app handled this better.

**Comment by cybercase** [comment]
Does this happen with a specific file or does it happen randomly with any file?

**Comment by WaferMouse** [comment]
With specific files, I've come across at least two (one FLAC and one MP3). Only seems to happen when I'm encoding to LP4.

**Comment by cybercase** [comment]
@WaferMouse If you could share those files with me, I'll try to reproduce the issue and maybe be I could be able to fix it.

**Comment by WaferMouse** [comment]
Can do! Here's the MP3, the FLAC is too big for me to attach though.
[bad files.zip](https://github.com/cybercase/webminidisc/files/5553174/bad.files.zip)

**Comment by cybercase** [comment]
Great!
I've been able to reproduce the issue and will look into it when I find some time
Thanks
