### ISSUE TITLE
24-bit audio?

### ISSUE THREAD

**Issue by OutragedBoss** [cybercase/webminidisc#26]
I was wondering if support for 24-bit audio could be added, at least for SP mode?  I know that type-R and later recorders can do 24-bit through the optical, but I'm not sure if Sony's NetMD protocol is limited to 16-bit.

Edit:  As a followup, I think every NetMD (released 2001) recorder is type-R (released 1999). So hopefully that indicates it could be supported.

**Comment by Invictaz** [comment]
Interesting find

**Comment by NetMDfan** [comment]
This article is worth reading: http://marlene-d.blogspot.com/2012/06/blast-from-past-minidisc-wide-bit.html?m=1 
Might it be that if you feed webminidisc 24 bit files, you will get 20 bit files on your MD?

**Comment by GrapheneCt** [comment]
As of now Web MiniDisc converts everything to 16 bit PCM: https://github.com/cybercase/webminidisc/blob/master/src/services/audio-export.ts#L95

**Comment by asivery** [comment]
NetMD only supports 16bit PCM, so uploading 24bit audio is impossible, and the audio will be converted to 16 bit PCM before transferring it to the machine, as GrapheneCt mentioned.
