### ISSUE TITLE
Remembering selected mode and title format

### ISSUE THREAD

**Issue by Shadester** [cybercase/webminidisc#31]
Not sure if you think that this is a good idea, but I feel like I usually do SP recording, so for me, having the SP selected by default makes sense. What could be done is using localStorage to store the setting for mode and title, so it will remember what you used last.

**Comment by cybercase** [comment]
@Shadester Yes, I think this could be useful.

I've already implemented a similar localStorage-based mechanism for a few settings like:
- dark mode : https://github.com/cybercase/webminidisc/blob/master/src/redux/app-feature.ts#L48
- trackTitleSource: https://github.com/cybercase/webminidisc/blob/master/src/redux/convert-dialog-feature.ts#L34

I can easily do the same for the recording format here: https://github.com/cybercase/webminidisc/blob/master/src/redux/convert-dialog-feature.ts#L30

**Comment by Shadester** [comment]
Ooh.. Cool. Then it would be like a two liner :)

I wonder if people also want LP4? It's probably not good enough for music, but maybe for podcasts or books?

**Comment by Shadester** [comment]
Awesome!
