### ISSUE TITLE
HAL deprecated in Fedora

### ISSUE THREAD

**Issue by alexjfinch** [cybercase/webminidisc#32]
Hi there,

Hal has been deprecated in Fedora since at least F16 and therefore when following;

https://github.com/glaubitz/linux-minidisc/tree/master/netmd/etc

You have nowhere to put 20-netmd.fdi as /usr/share/hal/fdi/information/20thirdparty/ doesn't exist.

Does this need to be used in current versions of Fedora or is this file no longer used?

Thanks!

**Comment by alexjfinch** [comment]
EDIT: I've found the solution as follows;

1) Create plugdev group
2) Add your user to it
3) Copy the udev rules file in
4) Rename it so it has a numerical value
5) Restorecon the file so SELinux allows it
6) Restart machine

**Comment by cybercase** [comment]
@alexjfinch Thanks for looking into this issue and sharing the solution. I'm not a linux expert and I've only had the chance to test the web app inside a Ubuntu VM.

I'm thinking of creating something like an FAQ or a Troubleshooting page for helping the people with the most common issues they might encounter while running the app. This might end up there :)

**Comment by alexjfinch** [comment]
I'm by no means a Linux expert! me and a friend were messing about with teamviewer last night to try and get this working.

You still need the netmd rules file, in the same place as per the link you've provided however just needs a few more steps than what they explain (the group etc). I can write out a fuller list of commands from my CLI history and replicate it on another machine (I have a Fedora laptop too that I can try) to fully test out the method and then paste it here to be included in your FAQ/Readme?

The .fdi file is no longer required in Fedora at least (I guess you found a place for it in Ubuntu).

**Comment by cybercase** [comment]
Thanks, that would be great.

**Comment by Shadester** [comment]
Would be great to have the FAQ linked from the Web MiniDisc page, so people can easily find it. And not only on the GitHub?

**Comment by cybercase** [comment]
Yes, absolutely. It's something I'll try to link from the main page to make sure it's well visible

**Comment by alexjfinch** [comment]
Here you go, I've just done this again step by step on my laptop and my MD connects perfectly.

############################################################
Instructions for Fedora and other distributions where Hal is now deprecated
############################################################

I completed all these actions from the root account.

1.) Navigate to the netmd rules file per the instructions and copy the
raw contents of netmd.rules to your clipboard

2.) Create a file in /etc/udev/rules.d using nano, ensure you use the same
rules name however give it a numerical value (I've used 80 in this instance)

"nano -w /etc/udev/rules.d/80-netmd.rules"

3.) Paste the contents of the raw output from Github here, exit and save.

4.) Use ls -laZ  command and ensure that root has ownership of the file, output

"-rw-r--r--. 1 root root unconfined_u:object_r:udev_rules_t:s0 3623 Jan 27 20:43 /
etc/udev/rules.d/80-netmd.rules"

Its important that the object states "object_r:udev_rules_t" I found it had something 
else when I saved the file another way

5.) Allow the file have the proper SELinux context using restorecon, use the following 
command;

"restorecon -v 80-netmd.rules"

6.) Create usergroup "plugdev" 

"groupadd plugdev"

7.) Add your user account to that group

"usermod -a -G plugdev <username>"

8.) Technically all you need to do now is logout and login to update your 
accounts group, however I just reboot, you don't need to add the .fdi file 
anywhere as its not required.

9.) Enjoy the app!
