### ISSUE TITLE
Q) Is it possible to transfer music designed for "gapless" recording/playback?

### ISSUE THREAD

**Issue by Liquidream** [cybercase/webminidisc#34]
Hi,
I'm really excited about this project & looking to source my first MD recorder as we speak (MZ-710).
However, it just occurred to me that a few of the albums I plan to use have seamless/gapless tracks.

**Is it currently possible with WebMinidisc to have "gapless" albums transferred** (e.g. from MP3's that have no gaps at end/beginning)?

If not, is that something that's possible/could be added to the "Wish List"?

Many thanks

Paul

**Comment by cybercase** [comment]
Hello @Liquidream, this is a question that I get fairly often.

AFAIK, the only way to have gapless playback on minidisc is to merge all the songs as into a single track, record that single track on a MD, and then add track marks at the end of each song.

Unfortunately, as of today, I couldn't find a way to programmatically set track marks via the NetMD protocol (I think that even the old sonicstage wasn't able to do this). This means that even if WebMinidisc joined all the songs into a single track, it wouldn't be able to set the track marks.

**Comment by Liquidream** [comment]
Hi @cybercase,

Thank you for the prompt reply (sorry to add more to the same Q pile!).
Ah, that's a shame - but sounds like there's not much more you can do.

Can track marks be set on the device (e.g. MZ-710) manually?
(Apologies if this is a rather basic Q - I'm new to MD's, so looking for possible "workarounds"! 😇)

**Comment by cybercase** [comment]
@Liquidream absolutely!

you can find the instructions here, at page 39: https://www.sony.com/electronics/support/res/manuals/3249/32495021M.pdf
