### ISSUE TITLE
Notification upon completion?

### ISSUE THREAD

**Issue by TeodorDumi** [cybercase/webminidisc#37]
Hey, thank you for making this! I've made so many discs with it and it's really great.

I was thinking, perhaps it would be neat to have an option to get a web notification when the current queue is done transferring? Especially in SP mode, transfers can take a lot of time. 

Not something necessary or high priority, but I believe it would be neat.

**Comment by cybercase** [comment]
Yes, it totally makes sense to me. I'm putting this into the todo list, thanks!

**Comment by cybercase** [comment]
I've added a new checkbox that you can use to enable web notifications upon completion.
The first time you check it a dialog will ask for confirmation before actually asking to enable web notifications.

I'm deploying the update right now, but it might take a couple of open/close your browser to get the update.
Once you've got it, let me know if everything works fine.

<img width="693" alt="Screenshot 2021-04-11 at 12 55 53" src="https://user-images.githubusercontent.com/1076854/114301463-54fc7c80-9ac5-11eb-8348-eb3f1939f2ad.png">

**Comment by TeodorDumi** [comment]
This is lovely! Thank you for the great work. It's working just right so far.
