### ISSUE TITLE
Can't detect my MZ N710

### ISSUE THREAD

**Issue by jms0784** [cybercase/webminidisc#38]
Hi folks,

I have a windows 10 PC, I access the Web Minidisc app using Chrome but the app doesn't detect my MZ N710 when I click connect.

Ironically the app detects my HI MD recorder (even though it provides an access denied), which I understand to be a USB issue.

Can anyone help me please?

Thank you.

**Comment by asivery** [comment]
@jms0784 Have you installed zadig?

**Comment by thedigitaljedi86** [comment]
I have the exact same issue.... my MZ N505 works without any issues
