### ISSUE TITLE
Copying titles no longer possible

### ISSUE THREAD

**Issue by dawkurp** [cybercase/webminidisc#51]
Hi!
Prior to the introduction of drag and drop reordering of tracks, full-width titling and groups it was possible to select all the text inside the application to copy the track titles and lengths as text into the clipboard.
Is there a way to achieve that functionality now? I used it extensively while making copies of music I've found on used MDs to archive them.

Thanks in advance for your help!

**Comment by cybercase** [comment]
Hello @dawkurp and thanks for your feedback. 
Unfortunately I didn't think of this use-case, but I'll try to come up with a quick solution and get back to you.

**Comment by dawkurp** [comment]
May I suggest a possible solution of putting the drag and drop reordering behind a toggle?
That way it's possible to also limit user error in using the app to rename tracks or just play specific tracks from the disc.

**Comment by cybercase** [comment]
@dawkurp I'll explore the toggle idea. Right now I came up with adding a drag-handle (it's still very rough... I'll take time to refine it).
Do you think it might work for your case?

Also, I'm mentioning @asivery who worked on the d&d for some extra feedback.

![t4P1bhQKFv](https://user-images.githubusercontent.com/1076854/126473094-10270902-9261-4c32-b7e3-73ebd32fc269.gif)

**Comment by cybercase** [comment]
@dawkurp BTW, as a temporary workaround you can still select and copy the track titles by switching to the _Retro Mode_.

**Comment by dawkurp** [comment]
Thanks for those solutions!
Both of them work for me, though I'll admit that the retro mode copied text gets a little scrambled formatting-wise, but I can fix that with a bit of regex on my end.

**Comment by asivery** [comment]
I didn't think of that use case either. I'd stay with the handle, though it should be smaller in my opinion - it currently shifts the interface by quite a lot.
