### ISSUE TITLE
Can't write or wipe disc

### ISSUE THREAD

**Issue by radishsam** [cybercase/webminidisc#52]
Can connect to and playback from device no worries.

Hi, thanks for this tool. I'm unable to write to older discs. Getting error: "Error uploading to device. There might not be enough space left." on all discs, including blank discs.

Tried to wipe disc and getting: "Oops… Something unexpected happened."

Player: MZ-N510, Windows 10

**Comment by asivery** [comment]
Can you post the errors you're getting in the JS Console?

**Comment by jamesprivett68** [comment]
Hi, I am currently having the same issue, but has only started recently.  I used to be able to write to Minidiscs with no issues (SP, LP2 & LP4 have all been written successfully in the past), but have tried again recently and get the "Error uploading to device. There might not be enough space left." even when trying to write a 4 minute track.  I have checked the discs are not write protected as I am able to wipe them, but not write to them once wiped

Player: Sony CMT-M333NT, Windows 7
