### ISSUE TITLE
Feature Request: "Title - Artist"

### ISSUE THREAD

**Issue by danmarker7** [cybercase/webminidisc#56]
I feel like it would be helpful if "Title - Artist" was a choice for naming songs added.

Also, any idea why some songs end up showing as Unknown Title but are titled in iTunes ?

**Comment by cybercase** [comment]
Hello @danmarker7 . I'll try to add the "Title - Artist" option for naming songs... it shouldn't be a big deal.

About the missing titles, it likely depends on the track's metadata... the library that I'm using to extract the metadata might not recognize correctly the tags, and that's the cause of the issue.
