### ISSUE TITLE
Use track number or name when recording

### ISSUE THREAD

**Issue by Siphonay** [cybercase/webminidisc#58]
Hello! First of all I want to thank you for making this app, I’m new to the MD world and I found it really easy and seamless to use, which to my understanding wasn’t much the case before

I’m writing this issue to suggest that, when recording a track, instead of naming the resulting file "wav.wav", it would instead be named "[track name].wav" or if it doesn’t have a title, something like "track [number].wav", so that risks of overwriting is lower when archiving a lot of minidiscs. I’m currently archiving a lot of unique and personal things recorded on MD, and it would definitely make things easier.

Thanks for your consideration, and have a nice day!

**Comment by cybercase** [comment]
Hello @Siphonay and thanks for your feedback.

I'm happy to see that you're using the _record_ feature of to archive the content of your older minidiscs.
I'll definitely take a look at the track naming and try to do something about that.

I'll keep you posted.

**Comment by Siphonay** [comment]
I just noticed that it actually gives a track name to the wav file if there is one − I didn’t actually try to record a track with a title before and I don’t know why I assumed it wouldn’t do that. Apologies for that, but my suggestion for tracks without names is still standing though!
