### ISSUE TITLE
Bug When Using Half-Width Katakana

### ISSUE THREAD

**Issue by depevauge** [cybercase/webminidisc#61]
Hi there,

I noticed a bug when naming titles using half-width katakana. Words that contain a _dakuten_ `゛` or _handakuten_ `゜` like `ロンドン` or `キャプテン` should be transliterated into `ﾛﾝﾄﾞﾝ` and `ｷｬﾌﾟﾃﾝ `respectively. However, any _daktuen_ or _handakuten_ will be omitted (resulting in `ﾛﾝﾄ ﾝ` and `ｷｬﾌ ﾃﾝ`). However, regular full-width _kana_ and _kanji_ seem to work just fine.

On a different note, please let me express **HOW HAPPY** I am about this brilliant piece of work.
Thank you so much for your effort, Stefano!

**Comment by cybercase** [comment]
Hello @depevauge and thanks, I'm really glad that you like the app :)

About the half-width katakana bug I'm summoning @andyboeh; he's the great guy who helped with adding the feature and definitely knows more than me about Japanese alphabets and transliteration.

Andy, do you think this might be related to the work you've done on full text titles? Or should we investigate in another direction?

**Comment by andyboeh** [comment]
@cybercase I don't think I've done any work on text titles - I just fixed support for Sharp devices.

**Comment by cybercase** [comment]
Oh my, you're right, I've tagged the wrong person, sorry for the trouble. Yes, I definitely meant @asivery , thanks

**Comment by depevauge** [comment]
I might have found a solution, actually! The error only occurs if you enter Katakana which are already half-size. If you use regular full-size Katakana, the app correctly transforms them into half-size ones.

**Comment by depevauge** [comment]
**Update:** I noticed that if you enter full-width Katakana or even Hiragana and don't edit the song name again, the entered text will be converted **correctly** into half-width Katakana. But as soon as you try to rename the song, any _dakuten_ and _handakuten_ will disappear.

Also, if you enter a _chōonpun_ `ー` (i.e. a dash that indicates a long preceding vowel) as in `オープニング`, it will not be transliterated correctly in whatever character the Mini Disc standard uses. In other words, the _chōonpun_ won't be displayed on any of my Japanese models, resulting in titles such as `ｵ ﾌﾟﾆﾝｸﾞ` when it should be `ｵｰﾌﾟﾆﾝｸﾞ`.

**Comment by depevauge** [comment]
**Update:** The half-width Katakana equivalent of a _chōonpun_ seems to be just the regular hyphen `-` in the Mini Disc charset (which is typographically incorrect by the way, but who cares).

**Comment by asivery** [comment]
Ok, I think I got it. When you type the dakuten as a separate character from the katakana, it doesn't get remapped correctly, and when the program can't find a remapped symbol it replaces it with a space. So typing テ|ズ|ト does work, but テ|ス|゛|ト| doesn't and the dakuten gets removed. Can you confirm if this is the case @depevauge ?

**Comment by depevauge** [comment]
Yes, that's exactly the problem I'm having. It also happens as soon as I edit a title that's already in half-width katakana. Also, it happens when I try to enter half-width Katakana direcrly, as the dakuten and handakuten are already treated as separate characters. Also, the chōonpun ought to be remapped to a regular hyphen (ラーメン →  ﾗ-ﾒﾝ) or an actual MD unit will display a space instead of the chōonpun.

**Comment by asivery** [comment]
Ok, great. I'll fix the dakuten problem. I can't replicate the chōonpun glitch though, can you base64-encode the exact character you're typing and send it here?

**Comment by depevauge** [comment]
The chōopun I'm typing is _44O8_ and should be mapped to the hyphen _LQ==_. I hope this is what you mean, I have absolutely zero programming skills. I'm just here for the support.

**Comment by asivery** [comment]
Ok @depevauge , I think I fixed the dakuten/handakuten issues. I can't fix the chōopun - the character you sent me is already mapped to the hyphen.

**Comment by depevauge** [comment]
Thank you so much! Can you check if _772w_ is also mapped to the hyphen? That's the half-width chōonpun in katakana. That might be the culprit and solve the problem.

**Comment by asivery** [comment]
Nope, that character wasn't mapped to the hyphen. It should work now. Are you perhaps on the Minidisc.wiki discord server? I could send you this version and you could check if that indeed fixed the problem.

**Comment by depevauge** [comment]
@asivery was very helpful and resolved all issues; I was able to verify this on a test build. One of the next updates will most likely incorporate these changes. Again, thank you so much!

![20210913_075249](https://user-images.githubusercontent.com/89867654/133239785-da3e9e59-ad80-40d8-b3b1-a772d4a5490a.jpg)

**Comment by cybercase** [comment]
Thanks to both of you for fixing this issue, @asivery and @depevauge 🙂 .
I'll definitely merge the fix and make a new release as soon as asivery is ready to open a PR.

**Comment by asivery** [comment]
@cybercase I have committed the fix onto my fork. I also added a few fixes/improvements:
- Fixed half-width katakana
- Fixed pause button in the track row
- Added MediaSession integration
- Added a way to overload serviceRegistry.netmdService if using this app in an electron environment (feel free to remove this if you feel this isn't a good addition to the project.)

Would you like me to open a PR?

**Comment by cybercase** [comment]
@asivery I'll try to look at the changes during the upcoming weekend, then I'll open a PR and we can discuss the changes there.
Thanks for your help.
