### ISSUE TITLE
possible to keep track of title name exhaustion?

### ISSUE THREAD

**Issue by arrjay** [cybercase/webminidisc#66]
per the UTOC layout at https://www.minidisc.org/md_toc.html, minidisc titling (half-width) is limited to 1785 characters total. I managed to hit this on my mz-n707 and started having issues uploading additional tracks.

would it be possible to keep track of this usage and possibly warn/alert if you're near the limit?

**Comment by asivery** [comment]
Hello @arrjay , WebMinidisc already keeps track of this limit. Can you elaborate on what issues are you getting when you approach this limit?

**Comment by arrjay** [comment]
here's a quick gif of the tracklilst I want to upload (note it's going to try using filename as the title). now, I don't get any warnings about it yet...
![upload jobset](https://arrjay.github.io/webmd-bugreport/upload_ui.gif)
click ok and the job starts. I get to track 44 and the application reports an "out of space" error
![uploading error](https://arrjay.github.io/webmd-bugreport/uploading.gif)
I browse the tracklist after and I see titles have been truncated starting on track 40
![result tracks](https://arrjay.github.io/webmd-bugreport/tracklist.gif)
I try to rename a track here, but I don't see a notice about being over UTOC limit
![track rename](https://arrjay.github.io/webmd-bugreport/rename.gif)

working to shorten all the track names seemed to do the trick, eventually, but I'm not seeing many alerts around exceeding the total track name limit here.

**Comment by asivery** [comment]
@arrjay I have implemented a solution to the problem you described. It's not merged into this project though. You can try it out by either compiling my fork of webminidisc, or by running the newest release of ElectronWMD. Please let me know if there's something you think is worth improving.
