### ISSUE TITLE
Sharp IM-DR400 can't write disc title

### ISSUE THREAD

**Issue by Jo2003** [cybercase/webminidisc#67]
Hi,
when trying to change disc title I get an "Oops" message with above stated NetMD recorder. 
OS is Windows 10 PRO. Writing tracks, editing track title works. So this is not the end of the world, but maybe this can be fixed. 

    store.ts:16 Error: Rejected
        at t [as constructor] (netmd-interface.ts:101)
        at new t (netmd-interface.ts:113)
        at e.<anonymous> (netmd-interface.ts:182)
        at 2.958ae84d.chunk.js?__WB_REVISION__=78f1097eea47067158d7:2
        at Object.next (2.958ae84d.chunk.js?__WB_REVISION__=78f1097eea47067158d7:2)
        at o (2.958ae84d.chunk.js?__WB_REVISION__=78f1097eea47067158d7:2)
    (anonymous) @ store.ts:16

Thanks for such great software!
   Jörg

**Comment by Jo2003** [comment]
Same problem with this device on an Ubuntu 20.04 based machine. Also tried incognito mode.

**Comment by seb4nihel** [comment]
Hi, have the same Problem with Sharp IM-DR410H.
As Jo2003 wrote, thanks for this great software!

**Comment by Jo2003** [comment]
Hi, unfortunately it doesn't work. Attached you'll find the log from the console. Hopefully it helps. If you need further information, please tell!

[IM-DR400-webminidisc.log](https://github.com/cybercase/webminidisc/files/7317309/IM-DR400-webminidisc.log)

Thanks in advance,
   Jörg

**Comment by asivery** [comment]
Ok, try this one @Jo2003 . I've made some changes: https://commitwmd.tiiny.site/webminidisc/

**Comment by Jo2003** [comment]
I made some tests with different tools. Writing the disc title on the Sharp recorder works with following byte streams:

 - get current disc title (used only for current length)

 - open disc header for write:
     `0x00, 0x18, 0x08, 0x10, 0x18, 0x02, 0x03, 0x00`
	
 - create store stream
```
    byte n1 = (new title length >> 8)
    byte n2 = (new title length & 0xff)
    byte o1 = (current title length >> 8)
    byte o2 = (current title length & 0xff)
	
    0x00, 0x18, 0x07, 0x02, 0x20, 0x18, 0x01, 0x00, 0x00, 0x30, 0x00, 0x0a, 0x00, 0x50, 0x00, n1, n2, 0x00, 0x00, o1, o2, title[0], title[1], ...
```

 - sync disc header 
    `0x00, 0x18, 0x08, 0x10, 0x18, 0x02, 0x00, 0x00`

Hope that helps!

**Comment by asivery** [comment]
@Jo2003 I have pushed an updated version of netmd-js that should solve this problem. Please let me know if you can rename discs using this version: https://github.com/asivery/netmd-js

**Comment by Jo2003** [comment]
It should work that way since you check the vendor and use the related command streams. 

I also made some further tests and code analysis. Could you try following command streams to check if this is compatible also with "critical" devices? 

* cache TOC
`0x00, 0x18, 0x08, 0x10, 0x18, 0x02, 0x03, 0x00`
* handshake 1
`0x00, 0x18, 0x08, 0x10, 0x18, 0x01, 0x01, 0x00`
* handshake 2
`0x00, 0x18, 0x08, 0x10, 0x18, 0x01, 0x00, 0x00`
* handshake 3
`0x00, 0x18, 0x08, 0x10, 0x18, 0x01, 0x03, 0x00
* set disc title as always
´0x18, 0x07, 0x02, 0x20, 0x18, 0x01, ...`
* handshake 4
`0x00, 0x18, 0x08, 0x10, 0x18, 0x01, 0x00, 0x00`
* sync TOC
`0x00, 0x18, 0x08, 0x10, 0x18, 0x02, 0x00, 0x00`

**Comment by thp** [comment]
This is probably fixed with https://github.com/cybercase/netmd-js/pull/29 since it removes the whole cache toc / handshake / sync toc and replaces it with the AV/C MD audio fixes.
