### ISSUE TITLE
NOT GAPLESS - Small gap between 2 titles belonging together

### ISSUE THREAD

**Issue by Jo2003** [cybercase/webminidisc#68]
Hi,
I found another minor issue. I ripped a CD without gaps between tracks (any live CD will have the same issue). I used EAC to extract the files into the WAV format. I have written the tracks in SP mode to MD. 

When playing the MD there now is a small gap between the tracks. Nothing critical, the gap is very short, but hearable.

**Comment by cybercase** [comment]
Hello @Jo2003  and thanks for reporting.
This issue has been discussed in #34 .

**Comment by Jo2003** [comment]
Thanks for the fast answer. I can't tell for sure for Sonic Stage, but I'm 100% sure that NetMD Simple Burner supports gapless recording (of course only in LP2 / LP4). This was the main feature why I started using minidisc at a very late point of time. 

And you're right: best way would be to record the disc at once and set the cuepoints later. But since we don't know how to do this through NetMD interface it doesn't help much. 

Nevertheless - thanks for your effort!
