### ISSUE TITLE
N910 not detected on Windows 10

### ISSUE THREAD

**Issue by emiel82** [cybercase/webminidisc#70]
Hi!
I like the application and use it a lot with my N505.
Recently started to use a N910 and it does not show up in the device list to connect on Windows 10.
On Mac OS 12 on my Mac Mini 2018 it works fine for both the N505 and N910.
Any thoughts?
Willing to share more information when required, please let me know.
Thanks, Emiel

**Comment by asivery** [comment]
@emiel82 Have you installed the Zadig driver?

**Comment by emiel82** [comment]
Hi @asivery , I did indeed. Just ran the Zadig installer from Sep. 2021 again to be sure. 
Both in Web MD and Platinum MD it does detect N505 but not N910 in Windows.

**Comment by emiel82** [comment]
![image](https://user-images.githubusercontent.com/93405028/139503271-7917ed37-a264-4d27-97fa-052e390802b3.png)
On the Mac (using Brave browser) it looks fine.

**Comment by emiel82** [comment]
Update: reinstalled Zadig again, re-connected and select the N910 without a problem.
Closed.
