### ISSUE TITLE
issues with macOS monterey?

### ISSUE THREAD

**Issue by sharkzor** [cybercase/webminidisc#71]
suddenly got 
title.flac: Error uploading to device. There might not be enough space left.

md n710. recording via line-in is working.

**Comment by emiel82** [comment]
I do get the error sometimes, most often when another error has occurred.
What works for me is unplugging the device, restarting the app and reconnecting the device.
Both on N505 and N910.

**Comment by cybercase** [comment]
I'll update to Monterey soon and check if everything works fine.

**Comment by sharkzor** [comment]
tried a windows 10 pc. same error
Error uploading to device. There might not be enough space left.
as soon as it tries to record.
might be the unit, but it started to record fine from line in

**Comment by cybercase** [comment]
I'm sorry about that. I've updated to Monterey and to the latest version of Chrome but everything works fine for me.

If I were you I'd try to:
- upload a different track (mp3 or wav) in SP mode
- try to erase the disc
- try with a different disc
- try with another unit

Hope it helps

**Comment by sharkzor** [comment]
tnx. erase works, renaming disk works, different disk doesn't matter.
my other unit has died sadly.

I've tried platinum md on windows 10 that did something, but it kept saying blank disk.
not sure what is going on here, but i guess the unit died.
