### ISSUE TITLE
Panasonic SJ-MR250 doesn't get recognized

### ISSUE THREAD

**Issue by FlabberQuestion** [cybercase/webminidisc#73]
Is it possible this unit is not known yet by the program? I assume that most populair net MD devices are defined somewhere in a file or dll so that the program knows what device it is? I have a sharp that works fine but this panasonic is not found. Do I need to submit a request somehwere to have this device added?

**Comment by cybercase** [comment]
Hello @Stealthius . All supported devices are listed here: https://github.com/cybercase/netmd-js/blob/master/src/netmd.ts 

If you plan to submit a PR to add your device-id, please also do some testing to make sure the device works well with the netmd-js library.

Thanks

**Comment by Stealthius** [comment]
Hi @cybercase. Thank you for replying. I'm willing to test as much as I can if I knew how to. Do I need to test something first before submitting a PR? I went to look at netmd-js, do I need to download something there to test with? I have absolutely no idea how Github works so I am very sorry if this strikes as being stupid. Any help would be greatly appreciated how I can test my device with netmd-js library.

**Comment by Stealthius** [comment]
The device is indeed not listed in de netmd.ts file. These are the device values from Device Manager: 
![image](https://user-images.githubusercontent.com/94482785/142197648-ea9c3bdb-9b09-49b0-9e13-98f803f1e805.png)
So I guess below needs to be added to the: `export const DevicesIds = [` section 
**{ vendorId: 0x04da, deviceId: 0x23b3, name: 'Panasonic SJ-MR250' },**

I'll go read about how to submit PR now
