### ISSUE TITLE
Odd behavior with MZ-NH600D

### ISSUE THREAD

**Issue by cbmtrx** [cybercase/webminidisc#76]
I had WebMinidisc working fine with an MZ-N420D. After I connected with an MZ-NH600D, however, it converts the first track, uploads, but then it seems to get stuck and it doesn't progress with writing anything. I tried a few times. I checked the minidisc in a regular deck and it's fine. The recorder is in the correct MD mode.

I switched to PlatinumMD and had no problems; worked just the same as with the N420D.

Any idea what might be going on? Was really hoping to use WebMinidisc with this recorder.

**Comment by emiel82** [comment]
Perhaps because the NH600D is a Hi-MD device? As example, in Hi-SP mode, it supposedly creates the same quality files with a better compression than regular Minidisc SP mode.

**Comment by cbmtrx** [comment]
It could be what's causing it. But I needed to create standard MDs so I had the NH600D in standard SP mode (standard minidisc too) but evidently there's something going which is stalling it.

**Comment by asivery** [comment]
@cbmtrx There's a bug regarding sequential upload of tracks in this version. Please check if the same issue persists in https://web.minidisc.wiki/

**Comment by cbmtrx** [comment]
Tested it again (new UI?) and it works now. Cheers!

Too bad the NH600D can't do better than the N420D speedwise but oh well.
