### ISSUE TITLE
Cannot add new music on windows using Chrome.

### ISSUE THREAD

**Issue by cam194** [cybercase/webminidisc#8]
The blue add button doesn't appear when you're using Chrome on Windows. Otherwise works perfectly.

**Comment by cybercase** [comment]
@cam194 Could you post a screenshot of the issue?

**Comment by cam194** [comment]
Hi,

thanks for getting back so quickly :)

This is what you get when you connect a MD recorder with a blank disc. as you can see the add button is missing from the bottom right. everything else works fine you can blank discs edit ones its just that that seems to have gone AWOL.

![image](https://user-images.githubusercontent.com/67191840/85201541-2c1db780-b2f8-11ea-8593-8cad6710f610.png)

**Comment by cybercase** [comment]
@cam194 no problem :)

I fear it might be just a matter of aspect ratio of the screen. Could you try to shrink the browser's window and see if the button appears at the bottom right?

**Comment by cam194** [comment]
Hi,

You're a magician! Thank you so much i never even thought it could be that!
glad it was something so simple.

thank you again :)
keep up the good work.

**Comment by cybercase** [comment]
Happy it's solved!

I'll try to fix the app layout to make it more _responsive_ so that it works well all the screen sizes.
