### ISSUE TITLE
files from minidisc to mac

### ISSUE THREAD

**Issue by JanHelgebostad** [cybercase/webminidisc#81]
I see this works well for transferring files from pc/mac to minidisc player. I have the opposite problem. 20 years ago i got my father to record stories from his life on a sony net md player. I would like to transfer these files to my mac to edit them and use them to make an audiobook. i know the files are there as i can listen to the unedited stories via headset, but struggle to get them transferred to my mac in an editable format. any advise?

**Comment by joshuadavila** [comment]
Minidisc format does not allow for music transference from device to computer.
The only way to backup your personal recordings is using the line out jack and record it using another device..
Unless you have an RH-1, this model is supposed to allow tranfers from device to computer.

**Comment by igorinsky-MD** [comment]
Hi, yes by now, as I know the only option to upload digitally is using a Sony RH-1 unit with Sony's own software Sonicstage, which converts the usb uploaded data to atrac3 or wav format and leave it on your hard drive.
In the other hand, the user asivery started the ElectronWMD that announces the future possibility to upload tracks, if I understood it correctly.
Cheers!

**Comment by asivery** [comment]
@JanHelgebostad Check out https://web.minidisc.wiki/. The version hosted there has support for downloading tracks back to the computer via USB for some players (firmware B1.600 only, for now). If your player isn't compatible, please let me know.
