### ISSUE TITLE
Cannot connect MZ-N505 Type-R "Unable To Claim Interface."

### ISSUE THREAD

**Issue by panicBoyMD** [cybercase/webminidisc#9]
OSX 10.11.6 (Max upgrade)
iMac (20-inch, Mid 2009)
Using Chrome Version 83.0.4103.116 (Official Build) (64-bit)

My Sony MZ-N505 Type-R will not complete connection.  The error message I get is "Unable To Claim Interface."  Anyone have any insights?  My MZ-NE410 hooks up just fine, but it has a "NoDisc" issue, and won't read discs.  How frustrating.

**Comment by andyboeh** [comment]
I've got a MZ-N505 Type-R as well and it works fine. However, I had to give Linux the proper permissions, I edited `/etd/udev/rules.d/89-netmd.rules` to contain:

```
ACTION!="add|remove", GOTO="usb_netmd_end"
SUBSYSTEMS=="usb", GOTO="usb_netmd_check"
GOTO="usb_netmd_end"

LABEL="usb_netmd_check"

ATTRS{idVendor}=="04dd", ATTRS{idProduct}=="9013", ACTION=="add", GROUP="users"
ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0084", ACTION=="add", GROUP="users"

LABEL="usb_netmd_end"
```
(The second ID is for the Sharp IM-DR420H, I don't remember which one is which). This gives members of the group "users" the required read/write rights on the device.

**Comment by asivery** [comment]
Issue outdated, please reopen if it's still relevant.
