### ISSUE TITLE
Mini Disc error

### ISSUE THREAD

**Issue by sunohara111** [cybercase/webminidisc#98]
Does anyone know how to fix the error message 'the discs title seems to be corrupted' when trying to upload mp3 files onto a mini disc? Thanks

**Comment by asivery** [comment]
Hello @sunohara111,
What device are you using?
Have you checked out https://web.minidisc.wiki/ ? It hosts a newer version of WebMinidisc, with the bug causing this error to show up patched.

**Comment by asivery** [comment]
Issue outdated, reopen if it's still relevant.
